@startuml
skinparam linetype ortho

entity User {
    *id: bigint
    --
    *name: varchar(255)
}

entity Review {
    *user_id: bigint <<FK>>
    *movie_id: bigint <<FK>>
    --
}

entity Movie {
    *id: bigint
    --
    *title: varchar(255)
}

User ||..o{ Review
Movie ||.o{ Review
@enduml
