gitGraph
  accTitle: Initial Git history

  commit id: "[0001]"
  commit id: "[0002]"
  commit id: "[0003]"
  branch feature/ratings
  commit id: "[0004] Generic rating component"
  commit id: "[0005] Movie rating system"
  commit id: "[0006] Comment rating system"
