---
config:
  er:
    layoutDirection: LR
---
erDiagram
  accTitle: Example database schema

  Post {
    bigint id PK
    text content
  }

  Comment {
    bigint id PK
    text content
    bigint post_id FK
  }

  Post ||--o{ Comment : ""
